Building configuration...

Current configuration:
!
frr version 8.4_git
frr defaults traditional
hostname pe-dc
domainname localdomain
no ipv6 forwarding
!
password zebra
!
interface eth1
 ip address 10.1.1.1/30
 ip ospf area 0
exit
!
interface eth2
 ip address 10.2.1.2/30
 ip ospf area 0
exit
!
interface lo
 ip address 2.2.2.2/32
 ip ospf area 0
exit
!
router bgp 65000
 bgp router-id 2.2.2.2
 neighbor 3.3.3.3 remote-as 65000
 neighbor 3.3.3.3 update-source lo
 !
 address-family ipv4 vpn
  neighbor 3.3.3.3 activate
 exit-address-family
exit
!
router ospf
 ospf router-id 2.2.2.2
exit
!
mpls ldp
 router-id 2.2.2.2
 !
 address-family ipv4
  discovery transport-address 2.2.2.2
  !
  interface eth1
  exit
  !
 exit-address-family
 !
exit
!
end
