import logging
import requests
import threading
from backend.config import OLLAMA_MODEL
logger = logging.getLogger(__name__)

# 1. Global lock for the LLM queue
llm_lock = threading.Lock()

class LLMEngine:
    def __init__(self, ollama_url: str = "http://localhost:11434", model_name: str = OLLAMA_MODEL):
        self.ollama_url = ollama_url.rstrip("/")
        self.model_name = model_name 
        self.generate_endpoint = f"{self.ollama_url}/api/generate"

    def _build_system_prompt(self) -> str:
        """
        Defines the strict persona and boundaries for the NOC Copilot.
        """
        return (
            "You are an autonomous, air-gapped Enterprise NOC Copilot. "
            "Your job is to analyze network telemetry, predicted faults, and internal runbooks to advise network operators. "
            "Rules you must strictly follow:\n"
            "1. You are operating in a highly secure environment. Do not suggest checking the internet or contacting external cloud support.\n"
            "2. Base your analysis ONLY on the provided context, telemetry, and topology data.\n"
            "3. If the answer is not in the context, state that you do not have sufficient internal documentation.\n"
            "4. Be direct, professional, and concise. Omit filler greetings."
        )

    def generate_incident_analysis(self, incident_json: str, rag_context: str) -> str:
        """
        Constructs the final prompt combining the Prediction Incident and RAG runbooks,
        then queries the local LLM using a thread lock to prevent overloading.
        """
        system_prompt = self._build_system_prompt()
        
        user_prompt = (
            f"An incident prediction has been generated by the predictive engine:\n{incident_json}\n\n"
            f"Here is the relevant internal topology and runbook data:\n{rag_context}\n\n"
            "Provide a root-cause hypothesis and the recommended corrective actions the NOC operator should take before the ETA."
        )

        full_prompt = f"{system_prompt}\n\nUser:\n{user_prompt}\n\nCopilot:"

        payload = {
            "model": self.model_name,
            "prompt": full_prompt,
            "stream": False,
            "options": {
                "temperature": 0.1,
                "top_p": 0.9
            },
            "think": False  
        }

        # The 'with' statement forces requests to queue up, one after the other
        with llm_lock:
            try:
                logger.info(f"Querying local LLM ({self.model_name}) at {self.ollama_url}...")
                logger.info(f"Prompt length: {len(full_prompt)} characters")
                logger.info(f"Prompt preview:\n{full_prompt[:500]}")
                response = requests.post(self.generate_endpoint, json=payload, timeout=260)
                response.raise_for_status()
                
                result = response.json()
                return result.get("response", "Error: Empty response from LLM.").strip()
                
            except requests.exceptions.RequestException as e:
                logger.error(f"Failed to communicate with local LLM: {str(e)}")
                return "Critical Error: Air-gapped LLM backend is unreachable. Ensure the local Ollama service is running."

if __name__ == "__main__":
    # Standalone Test
    logging.basicConfig(level=logging.INFO)
    engine = LLMEngine()
    
    mock_incident = '{"incident_id": "INC-1001", "device": "PE2", "fault_type": "Congestion buildup", "eta": 12}'
    mock_context = "Runbook - Congestion buildup: Shift traffic to the secondary MPLS path using TE tunnels."
    
    print("Testing LLM Engine communication...")
    # response = engine.generate_incident_analysis(mock_incident, mock_context)
    # print(f"\nLLM Response:\n{response}")
    
    print("\n(To execute the LLM call, uncomment the execution lines in the __main__ block.)")