import logging
import requests
import threading

logger = logging.getLogger(__name__)

llm_lock = threading.Lock()

class LLMEngine:
    def __init__(self, ollama_url: str = "http://localhost:11434", model_name: str = "local-model"):
        self.ollama_url = ollama_url.rstrip("/")
        self.model_name = model_name 
        self.generate_endpoint = f"{self.ollama_url}/api/generate"

    def _build_system_prompt(self, memory_context: str = "") -> str:
        """
        Defines the strict persona and boundaries for the NOC Copilot.
        """
        prompt = (
            "You are an autonomous, air-gapped Enterprise NOC Copilot. "
            "Your job is to analyze network telemetry, predicted faults, and internal runbooks to advise network operators. "
            "Rules you must strictly follow:\n"
            "1. You are operating in a highly secure environment. Do not suggest checking the internet or contacting external cloud support.\n"
            "2. Base your analysis ONLY on the provided context, telemetry, and topology data.\n"
            "3. If the answer is not in the context, state that you do not have sufficient internal documentation.\n"
            "4. Be direct, professional, and concise. Omit filler greetings.\n"
        )
        
        if memory_context:
            prompt += (
                f"\n[CRITICAL - PAST OPERATOR PREFERENCES & HISTORICAL HABITS]:\n"
                f"{memory_context}\n"
                f"Adhere strictly to the preferences stated directly above when preparing your response pattern."
            )
        return prompt

    def generate_incident_analysis(self, incident_json: str, rag_context: str, memory_context: str = "") -> str:
        """
        Constructs the final prompt combining the Prediction Incident, RAG runbooks, and operator memory context.
        """
        system_prompt = self._build_system_prompt(memory_context=memory_context)
        
        user_prompt = (
            f"An incident prediction has been generated by the predictive engine:\n{incident_json}\n\n"
            f"Here is the relevant internal topology and runbook data:\n{rag_context}\n\n"
            "Provide a root-cause hypothesis and the recommended corrective actions the NOC operator should take before the ETA."
        )

        full_prompt = f"{system_prompt}\n\nUser:\n{user_prompt}\n\nCopilot:"

        payload = {
            "model": self.model_name,
            "prompt": full_prompt,
            "stream": False,
            "options": {
                "temperature": 0.1,
                "top_p": 0.9
            }
        }

        with llm_lock:
            try:
                logger.info(f"Querying local LLM ({self.model_name}) at {self.ollama_url}...")
                response = requests.post(self.generate_endpoint, json=payload, timeout=260)
                response.raise_for_status()
                result = response.json()
                return result.get("response", "Error: Empty response from LLM.").strip()
            except requests.exceptions.RequestException as e:
                logger.error(f"Failed to communicate with local LLM: {str(e)}")
                return "Critical Error: Air-gapped LLM backend is unreachable. Ensure the local Ollama service is running."

    def generate_chat_answer(
        self,
        question: str,
        rag_context: str,
        incident_json: str | None = None,
        memory_context: str = ""
    ) -> str:
        """Operator chat endpoint grounded in historical operator contexts."""
        system_prompt = self._build_system_prompt(memory_context=memory_context)

        if incident_json:
            user_prompt = (
                f"Operator question:\n{question}\n\n"
                f"Related incident context (JSON):\n{incident_json}\n\n"
                f"Relevant internal runbooks/topology context:\n{rag_context}\n\n"
                "Answer the operator. If the context is insufficient, say what is missing."
            )
        else:
            user_prompt = (
                f"Operator question:\n{question}\n\n"
                f"Relevant internal runbooks/topology context:\n{rag_context}\n\n"
                "Answer the operator. If the context is insufficient, say what is missing."
            )

        full_prompt = f"{system_prompt}\n\nUser:\n{user_prompt}\n\nCopilot:"

        payload = {
            "model": self.model_name,
            "prompt": full_prompt,
            "stream": False,
            "options": {
                "temperature": 0.1,
                "top_p": 0.9,
            },
        }

        with llm_lock:
            try:
                logger.info(f"Querying local LLM ({self.model_name}) at {self.ollama_url} for chat...")
                response = requests.post(self.generate_endpoint, json=payload, timeout=260)
                response.raise_for_status()
                result = response.json()
                return result.get("response", "Error: Empty response from LLM.").strip()
            except requests.exceptions.RequestException as e:
                logger.error(f"Failed to communicate with local LLM: {str(e)}")
                return "Critical Error: Air-gapped LLM backend is unreachable. Ensure the local Ollama service is running."