frr version 8.4_git
frr defaults traditional
hostname edge-br
no ipv6 forwarding
!
password zebra
!
ip route 10.2.1.0/30 10.2.2.2
!
interface eth1
 ip address 10.2.2.1/30
exit
!
interface eth2
 ip address 192.168.2.1/24
exit
!
interface tun0
 ip ospf network broadcast
exit
!
router bgp 65002
 bgp router-id 5.5.5.5
 no bgp ebgp-requires-policy
 neighbor 10.0.0.1 remote-as 65001
 !
 address-family ipv4 unicast
  network 192.168.2.0/24
 exit-address-family
exit
!
log file /var/log/frr/frr.log informational
debug bgp neighbor-events
