Building configuration...

Current configuration:
!
frr version 8.4_git
frr defaults traditional
hostname p-core
domainname localdomain
no ipv6 forwarding
!
password zebra
!
interface eth1
 ip address 10.1.1.2/30
 ip ospf area 0
exit
!
interface eth2
 ip address 10.1.2.2/30
 ip ospf area 0
exit
!
interface lo
 ip address 1.1.1.1/32
 ip ospf area 0
exit
!
router ospf
 ospf router-id 1.1.1.1
exit
!
mpls ldp
 router-id 1.1.1.1
 !
 address-family ipv4
  discovery transport-address 1.1.1.1
  !
  interface eth1
  exit
  !
  interface eth2
  exit
  !
 exit-address-family
 !
exit
!
end
