Building configuration...

Current configuration:
!
frr version 8.4_git
frr defaults traditional
hostname pe-br
domainname localdomain
no ipv6 forwarding
!
password zebra
!
interface eth1
 ip address 10.1.2.1/30
 ip ospf area 0
exit
!
interface eth2
 ip address 10.2.2.2/30
 ip ospf area 0
exit
!
interface lo
 ip address 3.3.3.3/32
 ip ospf area 0
exit
!
router bgp 65000
 bgp router-id 3.3.3.3
 neighbor 2.2.2.2 remote-as 65000
 neighbor 2.2.2.2 update-source lo
 !
 address-family ipv4 vpn
  neighbor 2.2.2.2 activate
 exit-address-family
exit
!
router ospf
 ospf router-id 3.3.3.3
exit
!
mpls ldp
 router-id 3.3.3.3
 !
 address-family ipv4
  discovery transport-address 3.3.3.3
  !
  interface eth1
  exit
  !
 exit-address-family
 !
exit
!
end
